# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a23d2fe4c279876d4ca5e3a60085678949236457cfb5336a8db7743dbc95e9e2880ecdc6bc7b8554b557e0cb22addf97b159cb94027f0852d2b1f91c20b7b05c

test:
  secret_key_base: 0f1d51393a32dbe951a05f16c25b00b01afd3152d486323dc95790f54ca90c6e28089726c0df2dd05da2f41b88a649d2232dcec364ba58e996a878f7caaa10d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>



development:
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://127.0.0.1:3000
production:
  paypal_host: https://www.paypal.com
  app_host: https://launchschool.com/